/* AUTH */
// Login
export const USER_LOGIN = "USER_LOGIN";
export const FACEBOOK_LOGIN = "FACEBOOK_LOGIN";
// Signup
export const USERNAME_SIGNUP = "USERNAME_SIGNUP";
export const FACEBOOK_SIGNUP = "FACEBOOK_SIGNUP";

/* ONBOARDING */
// Non-Referral
export const NAVIGATE_NONREFERRAL_ONBOARDING_PROCESS = "NAVIGATE_NONREFERRAL_ONBOARDING_PROCESS";
export const SAVE_AVATAR_NAME = "SAVE_AVATAR_NAME";