/* GAME */
export const LOCAL_STATS = 'LOCAL_STATS';


/* AWS COGNITO */
export const COGNITO_ID = 'COGNITO_ID'; 
export const IS_LOGGED_IN = 'IS_LOGGED_IN';
export const USER_PROFILE = 'USER_PROFILE';
export const TOKEN_STORAGE = 'TOKEN_STORAGE';
export const INTEGRATION_REQUESTS = 'INTEGRATION_REQUESTS';
