/* Activities */
export const SET_AVATAR_ACTIVITY = 'SET_AVATAR_ACTIVITY';
export const SET_ACTIVE_ACTIVITY = 'SET_ACTIVE_ACTIVITY';
export const SET_ACTIVE_SEGMENT = 'SET_ACTIVE_SEGMENT';
export const UPDATE_ACTIVITIES_LIST = 'UPDATE_ACTIVITIES_LIST';

/* Analytics */
export const TRACK_NAVIGATION = 'TRACK_NAVIGATION';
export const TRACK_USER_BEHAVIOUR = 'TRACK_USER_BEHAVIOUR';
export const IDENTIFY_ANALYTICS_USER = 'IDENTIFY_ANALYTICS_USER';
export const ALIAS_ANON_TO_USER = 'ALIAS_ANON_TO_USER';


/* Stats */
export const UPDATE_STATS = 'UPDATE_STATS';
export const SET_DISPLAY_STATS = 'SET_DISPLAY_STATS';
export const UPDATE_LOCAL_STATS = 'UPDATE_LOCAL_STATS';
export const GET_LOCAL_STATS = 'GET_LOCAL_STATS';



/* Goals */
export const TOGGLE_DAILY_GOALS_DISPLAY = 'TOGGLE_DAILY_GOALS_DISPLAY';


/* User */
export const TOGGLE_LOCAL_GAME_MODE = 'TOGGLE_LOCAL_GAME_MODE';
export const UPDATE_USER = 'UPDATE_USER';

/* Auth */
export const SIGN_IN_USER = 'SIGN_IN_USER';
export const SIGN_OUT_USER = 'SIGN_OUT_USER';
export const GET_COGNITO_PROFILE = 'GET_COGNITO_PROFILE';
export const UPDATE_INTEGRATION_REQUEST_IDS = 'UPDATE_INTEGRATION_REQUEST_IDS';

/* Days */
export const UPDATE_DAYS = 'UPDATE_DAYS';

